yfinance:
  tickers:
    - COP=X     # USD/COP
    - BZ=F      # Brent
    - ^VIX      # VIX
    - DX-Y.NYB  # DXY (ICE)
    - EMB       # iShares JPM EM Bond ETF
    - EMLC      # EM local currency debt ETF
    - LEMB      # EM local currency bond ETF
    - FEMB      # EM local currency bond ETF
    - ICOL      # MSCI Colombia ETF
    - GXG       # MSCI Colombia alternative ETF
    - CIB       # Bancolombia ADR
    - ^TNX      # US 10Y Treasury Yield
    - KC=F      # Coffee futures
    - MTF=F     # Newcastle coal futures
    - GC=F      # Gold futures
    - USDCLP=X  # USD/CLP
    - USDMXN=X  # USD/MXN
  period_years: 5
  interval: 1d
news:
  enabled: true
  keywords: ["peso", "dolar", "dolar", "USDCOP", "TRM", "Brent", "petroleo", "petroleo", "tasa", "inflacion", "inflacion", "TES"]
  sources_csv: info_sources.csv
llm:
  enabled: false
  provider: null
  model: null
storage:
  base_dir: data
reports:
  dir: reports/briefings
locale:
  language: es
  timezone: America/Bogota
