yfinance:
  tickers:
    - COP=X     # USD/COP
    - BZ=F      # Brent
    - ^VIX      # VIX
    - DX-Y.NYB  # DXY (ICE)
  period_years: 5
  interval: 1d
investiny:
  enabled: true
  interval: D
  lookback_days: 365
  instruments:
    col_bond_5y:
      id: 29240
      alias: COL_BOND_5Y
    col_bond_10y:
      id: 29236
      alias: COL_BOND_10Y
news:
  enabled: true
  keywords: ["peso", "dólar", "dolar", "USDCOP", "TRM", "Brent", "petróleo", "petroleo", "tasa", "inflación", "inflacion", "TES"]
  sources_csv: info_sources.csv
llm:
  enabled: false
  provider: null
  model: null
storage:
  base_dir: data
reports:
  dir: reports/briefings
locale:
  language: es
  timezone: America/Bogota
