name: Daily Briefing

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily pipeline
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          NEWS_USER_AGENT: ${{ secrets.NEWS_USER_AGENT }}
        run: python src/scripts/daily_update.py --date today

      - name: Upload briefing artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: daily-briefing-${{ github.run_id }}
          path: |
            reports/briefings/
            reports/relations/
          retention-days: 14
