name: Daily Briefing

on:
  schedule:
    - cron: '0 10 * * 1-5'  # 10:00 UTC, lunes-viernes
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily update
        run: |
          python -m src.scripts.daily_update --date today --config config/settings.yaml

      - name: Upload briefing artifacts
        uses: actions/upload-artifact@v4
        with:
          name: briefing-${{ github.run_id }}
          path: |
            reports/briefings/*.md
            reports/briefings/*.html
            data/processed/market_daily.parquet

